Feat: Team of agents
l3vels/L3AGI pull request #27
Opened 2023-09-07 12:24 UTC by okradze

2023-09-07 13:12 UTC, Chkhikvadze requested changes

2023-09-07 13:12 UTC, Chkhikvadze commented on apps/server/agents/plan_and_execute/l3_plan_and_execute.py
>          memory.ai_name = "AI"
Do we need to use the agent name?

2023-09-07 13:12 UTC, Chkhikvadze commented on apps/server/agents/plan_and_execute/l3_plan_and_execute.py
> +            print(err)
remvove it

2023-09-08 13:24 UTC, okradze commented on apps/server/agents/plan_and_execute/l3_plan_and_execute.py
>          memory.ai_name = "AI"
changed to agent name

2023-09-08 13:35 UTC, merged