Feat/send voice
l3vels/L3AGI pull request #290
Opened 2023-11-07 14:46 UTC by levanion

2023-11-07 14:57 UTC, okradze requested changes

2023-11-07 14:57 UTC, okradze commented on apps/ui/src/components/AudioPlayer/AudioPlayer.tsx
> +  const progressBarRef = useRef(null as any)
fix ref types

2023-11-07 14:59 UTC, merged

2023-11-08 12:59 UTC, levanion commented on apps/ui/src/services/chat/useCreateChatMessageService.ts
> +          voice_url: voice_url,
done

2023-11-08 12:59 UTC, levanion commented on apps/ui/src/components/AudioRecorder/AudioRecorder.tsx
> +      console.log(e)
done

2023-11-08 13:00 UTC, levanion commented on apps/ui/src/components/AudioPlayer/AudioPlayer.tsx
> +  const progressBarRef = useRef(null as any)
done

2023-11-08 13:00 UTC, levanion commented on apps/ui/src/components/AudioRecorder/AudioRecorder.tsx
> +      console.error('Error accessing the microphone:', err)
done

2023-11-08 13:00 UTC, levanion commented on apps/ui/src/components/AudioPlayer/AudioPlayer.tsx
> +  /* background: ${({ theme }) => theme.body.backgroundColorPrimary}; */
done